const COURSES = [
  { title: "Frontend разработка", description: "Современная веб-разработка: от вёрстки до React.", duration: "6 месяцев", levelKey: "beginner", iconKey: "react", price: 15000, topics: ["HTML и CSS", "JavaScript", "React", "TypeScript"], langs: ["HTML", "CSS", "JavaScript", "TypeScript", "React"], students: 120, projects: 5, about: "Курс охватывает всё — от вёрстки до деплоя. Ты научишься создавать современные сайты и веб-приложения с нуля и выйдешь на рынок с портфолио." },
  { title: "Backend разработка", description: "Серверная разработка, базы данных и API.", duration: "6 месяцев", levelKey: "intermediate", iconKey: "database", price: 16000, topics: ["Node.js", "Базы данных и SQL", "REST API", "Docker и деплой"], langs: ["Python", "Node.js", "SQL", "Docker", "REST API"], students: 95, projects: 4, about: "Глубокое погружение в серверную разработку: базы данных, API, деплой. После курса ты сможешь строить масштабируемые backend-системы." },
  { title: "UI/UX дизайн", description: "Проектирование интерфейсов, которыми приятно пользоваться.", duration: "4 месяца", levelKey: "beginner", iconKey: "brush", price: 12000, topics: ["Основы дизайна", "Figma", "UX-исследования", "Прототипирование"], langs: ["Figma", "Adobe XD", "Principle", "Protopie"], students: 80, projects: 6, about: "Научишься думать как дизайнер и создавать интерфейсы, которые работают. Практика на реальных проектах с фидбеком от ментора." },
  { title: "Data Science", description: "Анализ данных и машинное обучение.", duration: "8 месяцев", levelKey: "advanced", iconKey: "chart", price: 18000, topics: ["Python для данных", "Pandas и NumPy", "Машинное обучение", "Визуализация"], langs: ["Python", "Pandas", "NumPy", "Sklearn", "Jupyter"], students: 60, projects: 3, about: "Машинное обучение, анализ данных, визуализация. Ты научишься находить смысл в больших массивах данных и строить модели." },
  { title: "Кибербезопасность", description: "Этичный хакинг и защита сетей.", duration: "6 месяцев", levelKey: "intermediate", iconKey: "shield", price: 16000, topics: ["Основы сетей и Linux", "Пентестинг", "Защита систем", "Анализ трафика"], langs: ["Linux", "Kali", "Wireshark", "Metasploit", "Python"], students: 45, projects: 3, about: "Этичный хакинг, пентестинг, защита сетей. Курс для тех, кто хочет работать в сфере информационной безопасности." },
  { title: "Мобильная разработка", description: "Приложения для iOS и Android.", duration: "6 месяцев", levelKey: "intermediate", iconKey: "phone", price: 15000, topics: ["Основы Dart и Flutter", "Работа с API", "Firebase", "Публикация в сторах"], langs: ["Swift", "Kotlin", "Flutter", "Dart", "Firebase"], students: 70, projects: 4, about: "Разработка мобильных приложений под iOS и Android. Создашь несколько приложений и опубликуешь их в сторе." },
];

const TEACHERS = [
  { name: "Алена Нурбекова", role: "Senior Frontend Mentor", experience: "5+ лет опыта", subjects: ["React", "TypeScript", "Next.js", "Web Animation"], bio: "Практикующий frontend-разработчик, обучает на реальных проектах." },
  { name: "Бектур Султанов", role: "Backend Team Lead", experience: "7+ лет опыта", subjects: ["Node.js", "Python", "PostgreSQL", "REST API"], bio: "Руководит backend-командой, учит строить надёжные сервисы." },
  { name: "Мария Жумабаева", role: "UI/UX Coach", experience: "6+ лет опыта", subjects: ["Figma", "UX Research", "Prototyping", "Design Systems"], bio: "Дизайнер интерфейсов, помогает собрать сильное портфолио." },
];

module.exports = { COURSES, TEACHERS };